apiVersion: v2
name: shopping-list
description: Lightweight shopping list web application
type: application
version: v0.1.0
appVersion: "v0.1.0"
keywords:
  - shopping
  - list
  - grocery
home: https://github.com/steled/shopping-list
sources:
  - https://github.com/steled/shopping-list
maintainers:
  - name: DGOPS
    email: dgops-kubernetes@datagroup.de
