{{- if eq .Values.networking.type "ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shopping-list.fullname" . }}
  labels:
    {{- include "shopping-list.labels" . | nindent 4 }}
  {{- with .Values.networking.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.networking.ingress.className }}
  ingressClassName: {{ .Values.networking.ingress.className | quote }}
  {{- end }}
  {{- if .Values.networking.ingress.hostname }}
  rules:
    - host: {{ .Values.networking.ingress.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "shopping-list.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- end }}
  {{- with .Values.networking.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
