{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shopping-list.fullname" . }}
  labels:
    {{- include "shopping-list.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "auth.username is required" .Values.auth.username | quote }}
  password: {{ required "auth.password is required" .Values.auth.password | quote }}
  session-secret: {{ required "auth.sessionSecret is required" .Values.auth.sessionSecret | quote }}
{{- end }}
